/home/io/miniconda3/envs/tanet/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/second/pytorch/models/tanet.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = edict(yaml.load(f))
.FFFE
======================================================================
ERROR: test_fit (tools.perception.object_detection_3d.voxel_object_detection_3d.test_object_detection_3d.TestVoxelObjectDetection3DLearner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/io/OpenDR/opendr_internal/tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py", line 101, in test_fit
    test_model(name, config)
  File "/home/io/OpenDR/opendr_internal/tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py", line 91, in test_model
    learner = VoxelObjectDetection3DLearner(model_config_path=config)
  File "/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_learner.py", line 73, in __init__
    self.__create_model()
  File "/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_learner.py", line 413, in __create_model
    ) = second_create_model(self.model_config_path, )
  File "/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/second/load.py", line 44, in create_model
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './perception/object_detection_3d/voxel_object_detection_3d/second/configs/tanet/car/test_short.proto'

======================================================================
FAIL: test_sources_are_clang_format_compliant (test_clang_format.TestClangFormat)
Test that sources are ClangFormat compliant.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/io/OpenDR/opendr_internal/tests/sources/test_clang_format.py", line 138, in test_sources_are_clang_format_compliant
    msg='Source file "%s" is not compliant with ClangFormat:\n\nDIFF:%s' % (source, diff)
AssertionError: False is not true : Source file "/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/second/core/cc/point_cloud_ops.cc" is not compliant with ClangFormat:

DIFF:*** 

--- 

***************

*** 3,10 ****

  
  PYBIND11_MODULE(point_cloud_ops_cc, m) {
    m.doc() = "pybind11 example plugin";
!   m.def("points_to_voxel", &points_to_voxel<float, 3>, "matrix tensor_square", "points"_a = 1, "voxels"_a = 2, "coors"_a = 3,
!         "num_points_per_voxel"_a = 4, "voxel_size"_a = 5, "coors_range"_a = 6, "max_points"_a = 7, "max_voxels"_a = 8);
!   m.def("points_to_voxel", &points_to_voxel<double, 3>, "matrix tensor_square", "points"_a = 1, "voxels"_a = 2, "coors"_a = 3,
!         "num_points_per_voxel"_a = 4, "voxel_size"_a = 5, "coors_range"_a = 6, "max_points"_a = 7, "max_voxels"_a = 8);
  }
--- 3,14 ----

  
  PYBIND11_MODULE(point_cloud_ops_cc, m) {
    m.doc() = "pybind11 example plugin";
!   m.def("points_to_voxel", &points_to_voxel<float, 3>, "matrix tensor_square",
!         "points"_a = 1, "voxels"_a = 2, "coors"_a = 3,
!         "num_points_per_voxel"_a = 4, "voxel_size"_a = 5, "coors_range"_a = 6,
!         "max_points"_a = 7, "max_voxels"_a = 8);
!   m.def("points_to_voxel", &points_to_voxel<double, 3>, "matrix tensor_square",
!         "points"_a = 1, "voxels"_a = 2, "coors"_a = 3,
!         "num_points_per_voxel"_a = 4, "voxel_size"_a = 5, "coors_range"_a = 6,
!         "max_points"_a = 7, "max_voxels"_a = 8);
  }


======================================================================
FAIL: test_sources_have_license (test_license.TestLicense)
Test that sources have the license.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/io/OpenDR/opendr_internal/tests/sources/test_license.py", line 139, in test_sources_have_license
    (source, APACHE2_LICENSE_PYTHON)
AssertionError: False is not true : Source file "/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/datasets/create_data_kitti.py" doesn't contain the correct Apache 2.0 License:

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

======================================================================
FAIL: test_pep8_conformance (test_pep8.TestCodeFormat)
Test that the tests are PEP8 compliant.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/io/OpenDR/opendr_internal/tests/sources/test_pep8.py", line 173, in test_pep8_conformance
    msg='PEP8 errors:\n%s' % (report)
AssertionError: 3 != 0 : PEP8 errors:
Report:
/home/io/OpenDR/opendr_internal/src/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d_learner.py:49:129: E501: line too long (130 > 128 characters)
/home/io/OpenDR/opendr_internal/tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py:19:129: E501: line too long (132 > 128 characters)
/home/io/OpenDR/opendr_internal/tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py:158:1: W391: blank line at end of file


----------------------------------------------------------------------
Ran 5 tests in 3.611s

FAILED (failures=3, errors=1)
:::Data Ready:::
Error: ./tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_temp/tanet_xyres_16_pretrained - No such file or directory.
Error: ./tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_temp - No such file or directory.
